// 301.sh feed (M5, spec §9) — alarm-driven polling that files posts in the same
// inbox as watch regressions.
//
// Two rules shape everything here:
//
//   1. Nothing happens until the user opts in. While `enabled` is false there is
//      no alarm and no request — the feed is never fetched "just to be ready".
//   2. Enabling seeds the seen-set instead of filing the backlog. Switching on a
//      news feature and being handed seventeen unread items is indistinguishable
//      from spam, and it buries a real regression sitting in the same inbox.
//
// The notification is optional decoration on top: the inbox entry is what every
// user gets, exactly as with regressions, because the notifications permission
// is optional and many will decline it.

import { type InboxItem, type NewsItem, type StorageLayer, storage } from '@/shared/storage';

export const NEWS_FEED_URL = 'https://301.sh/posts.json';
export const NEWS_ALARM = 'agent-readiness:news';
/** The blog ships a few posts a week; six hours is far below any real cadence. */
export const NEWS_PERIOD_HOURS = 6;
/** A burst of posts becomes at most this many inbox entries per cycle. */
export const MAX_NEW_PER_CYCLE = 3;

/**
 * One entry of https://301.sh/posts.json (`posts` array, OLDEST FIRST).
 *
 * The feed is generated by the 301.sh repo (`scripts/build-agents.mjs`) and its
 * shape and ordering are a documented contract — `docs/distribution.md` there,
 * section "Фид /posts.json — контракт". If posts stop arriving, compare the
 * live feed against this interface before touching anything here.
 */
export interface NewsPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  url: string;
  image?: string;
  tags?: string[];
}

export interface NewsDeps {
  store: StorageLayer;
  fetchPosts: () => Promise<NewsPost[]>;
  /** Best-effort toast; the inbox entry is written either way. */
  notify?: (item: NewsItem) => Promise<void>;
  now?: () => number;
}

/** Defensive: a feed entry without these two is not something we can file. */
function isUsable(post: NewsPost): boolean {
  return typeof post?.slug === 'string' && post.slug.length > 0 && typeof post?.url === 'string' && post.url.length > 0;
}

export function newsItemFrom(post: NewsPost, at: number): NewsItem {
  return {
    kind: 'news',
    id: `news:${post.slug}`,
    at,
    title: post.title,
    body: post.description ?? '',
    url: post.url,
  };
}

/**
 * Fetches the feed over the network. Kept separate from the cycle so tests
 * drive `runNewsCycle` with plain data and never touch fetch.
 */
export async function fetchNewsPosts(): Promise<NewsPost[]> {
  const response = await fetch(NEWS_FEED_URL, { headers: { 'cache-control': 'no-cache' } });
  if (!response.ok) throw new Error(`news feed: HTTP ${response.status}`);
  const data = (await response.json()) as { posts?: unknown };
  return Array.isArray(data.posts) ? (data.posts as NewsPost[]).filter(isUsable) : [];
}

/**
 * One feed cycle. Returns the ids filed, so a caller can decide whether the
 * badge needs repainting.
 *
 * `seedOnly` marks everything currently in the feed as seen and files nothing —
 * that is the enable path. A cycle that runs before seeding ever succeeded
 * seeds silently too, so a network failure at enable time cannot turn the whole
 * backlog into unread items on the next tick.
 */
export async function runNewsCycle(deps: NewsDeps, opts: { seedOnly?: boolean } = {}): Promise<{ filed: string[] }> {
  const { store, fetchPosts, notify, now = Date.now } = deps;
  const settings = await store.getNewsSettings();
  if (!settings.enabled && !opts.seedOnly) return { filed: [] };

  let posts: NewsPost[];
  try {
    posts = await fetchPosts();
  } catch (error) {
    // A feed that is down is not a user-facing event: say nothing, keep the
    // seen-set untouched, and let the next tick try again.
    console.warn('[agent-readiness] news feed check failed', error);
    return { filed: [] };
  }

  const seen = new Set(settings.seen);
  // Validated here and not only in fetchNewsPosts: the cycle must not depend on
  // who handed it the posts.
  const fresh = posts.filter((post) => isUsable(post) && !seen.has(post.slug));
  // The feed is oldest-first; reverse a COPY so the per-cycle cap keeps the
  // newest. The seen-set below stays in feed order on purpose — it is capped
  // with slice(-N), so a newest-first list would drop the newest slugs first
  // and re-file them forever.
  const newestFirst = [...fresh].reverse();
  const seeding = opts.seedOnly || !settings.seeded;

  const filed: string[] = [];
  if (!seeding) {
    for (const post of newestFirst.slice(0, MAX_NEW_PER_CYCLE)) {
      const item = newsItemFrom(post, now());
      await store.addAlert(item);
      filed.push(item.id);
      if (notify) {
        try {
          await notify(item);
        } catch (error) {
          // delivery is best-effort — a failed toast must not abort the cycle
          // and strand the remaining posts unfiled
          console.warn('[agent-readiness] news notification failed', error);
        }
      }
    }
  }

  // Every fresh slug is marked seen, including the ones the per-cycle cap
  // dropped: they are old news by the next tick, and filing them a cycle later
  // would look like the feed stuttered.
  if (fresh.length > 0 || !settings.seeded) {
    await store.updateNewsSettings({
      seen: [...settings.seen, ...fresh.map((post) => post.slug)],
      seeded: true,
    });
  }
  return { filed };
}

/** The slice of chrome.alarms this module needs — injectable for tests. */
export interface AlarmsLike {
  get(name: string): Promise<{ periodInMinutes?: number } | undefined>;
  create(name: string, info: { periodInMinutes?: number; delayInMinutes?: number }): Promise<void> | void;
  clear(name: string): Promise<boolean> | boolean;
}

/**
 * (Re)creates the alarm from settings. Same rule as the watch alarm: creating
 * an alarm that already exists RESTARTS its countdown, and an MV3 worker starts
 * on every event, so an unconditional create would push a six-hour period
 * forward forever.
 */
export async function scheduleNews(store?: StorageLayer, alarms?: AlarmsLike): Promise<void> {
  const api = alarms ?? ((await import('wxt/browser')).browser.alarms as unknown as AlarmsLike);
  const layer = store ?? (await storage());
  const { enabled } = await layer.getNewsSettings();
  if (!enabled) {
    await api.clear(NEWS_ALARM);
    return;
  }
  const periodInMinutes = NEWS_PERIOD_HOURS * 60;
  const existing = await api.get(NEWS_ALARM);
  if (existing?.periodInMinutes === periodInMinutes) return;
  await api.create(NEWS_ALARM, { periodInMinutes, delayInMinutes: 1 });
}

/** Enable path: seed first, then start the clock. */
export async function enableNews(deps: NewsDeps, alarms?: AlarmsLike): Promise<void> {
  await deps.store.updateNewsSettings({ enabled: true, seeded: false });
  await runNewsCycle(deps, { seedOnly: true });
  await scheduleNews(deps.store, alarms);
}

export async function disableNews(store: StorageLayer, alarms?: AlarmsLike): Promise<void> {
  await store.updateNewsSettings({ enabled: false });
  await scheduleNews(store, alarms);
}

/** Inbox entries this module owns, newest first — for the UI. */
export function newsFrom(items: readonly InboxItem[]): NewsItem[] {
  return items.filter((item): item is NewsItem => item.kind === 'news').sort((a, b) => b.at - a.at);
}
