// Generated by scripts/build-icons.mjs — do not edit by hand.
export const ICON_NAMES = [
  'scan',
  'pass',
  'fail',
  'na',
  'warn',
  'info',
  'copy',
  'external',
  'settings',
  'history',
  'watch',
  'chevron-down',
  'chevron-up',
  'theme',
  'save',
  'saved',
  'dashboard',
] as const;
export type IconName = (typeof ICON_NAMES)[number];
