// Icon sprite builder — 301-ui/RI sprite principle, our own icons from MDI.
// Source: @mdi/svg (Pictogrammers Material Design Icons, Apache-2.0).
// Every symbol is forced to fill="currentColor" with no baked backgrounds, so
// both color themes drive icon color via CSS `color`.
//
// Outputs (committed, regenerate with `npm run build:icons`):
//   src/assets/icons-sprite.svg   — <symbol id="i-mono-{name}"> sprite
//   src/shared/icon-names.ts      — generated IconName union + list
//   dev/icons-preview.html        — visual check in both themes

import fs from 'node:fs';
import path from 'node:path';
import { optimize } from 'svgo';

// our-name -> @mdi/svg file name (extend as the UI grows)
const ICONS = {
  scan: 'radar',
  pass: 'check-circle-outline',
  fail: 'close-circle-outline',
  na: 'minus-circle-outline',
  warn: 'alert-circle-outline',
  info: 'information-outline',
  copy: 'content-copy',
  external: 'open-in-new',
  settings: 'cog-outline',
  history: 'history',
  watch: 'bell-outline',
  'chevron-down': 'chevron-down',
  'chevron-up': 'chevron-up',
  theme: 'theme-light-dark',
};

const ROOT = process.cwd();
const MDI_DIR = path.join(ROOT, 'node_modules', '@mdi', 'svg', 'svg');
const OUT_SPRITE = path.join(ROOT, 'src', 'assets', 'icons-sprite.svg');
const OUT_NAMES = path.join(ROOT, 'src', 'shared', 'icon-names.ts');
const OUT_PREVIEW = path.join(ROOT, 'dev', 'icons-preview.html');

const symbols = [];
for (const [name, mdiName] of Object.entries(ICONS)) {
  const file = path.join(MDI_DIR, `${mdiName}.svg`);
  if (!fs.existsSync(file)) {
    console.error(`[icons] missing in @mdi/svg: ${mdiName} (for "${name}")`);
    process.exit(1);
  }
  const { data } = optimize(fs.readFileSync(file, 'utf8'), {
    multipass: true,
    // svgo v4: removeViewBox is no longer in preset-default — viewBox survives as-is
    plugins: ['preset-default'],
  });
  const inner = data
    .replace(/^<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    // transparency for two themes: strip any baked fill, inherit currentColor
    .replace(/\s*fill="[^"]*"/g, '')
    .replace(/<path /g, '<path fill="currentColor" ');
  symbols.push(`<symbol id="i-mono-${name}" viewBox="0 0 24 24">${inner}</symbol>`);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols.join('\n')}\n</svg>\n`;
fs.writeFileSync(OUT_SPRITE, sprite, 'utf8');

const names = Object.keys(ICONS);
fs.writeFileSync(
  OUT_NAMES,
  `// Generated by scripts/build-icons.mjs — do not edit by hand.\n` +
    `export const ICON_NAMES = [\n${names.map((n) => `  '${n}',`).join('\n')}\n] as const;\n` +
    `export type IconName = (typeof ICON_NAMES)[number];\n`,
  'utf8',
);

fs.mkdirSync(path.dirname(OUT_PREVIEW), { recursive: true });
const items = names
  .map((n) => `<div class="item"><svg width="24" height="24"><use href="#i-mono-${n}"/></svg>${n}</div>`)
  .join('\n');
fs.writeFileSync(
  OUT_PREVIEW,
  `<!doctype html><meta charset="utf-8"><title>Icons preview</title>
<style>
  body{font:12px system-ui;display:flex;margin:0}
  .pane{flex:1;padding:24px;display:grid;grid-template-columns:repeat(auto-fill,minmax(90px,1fr));gap:16px;align-content:start}
  .light{background:#fff;color:#1a1a1a}.dark{background:#16181d;color:#e6e6e6}
  .item{text-align:center}.item svg{display:block;margin:0 auto 4px}
</style>
${sprite}
<div class="pane light">${items}</div>
<div class="pane dark">${items}</div>\n`,
  'utf8',
);

console.log(`[icons] ${names.length} icons -> icons-sprite.svg, icon-names.ts, dev/icons-preview.html`);
